services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: poetry run flask run --host=0.0.0.0 --reload