services:
  backend:
    container_name: housetour
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - ./public:/app/public
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: poetry run flask run --host=0.0.0.0 --reload
