name: Image
description: Push docker image
inputs:
  github-token:
    description: 'GitHub token for deployment'
    required: true
runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - id: repo-name
      name: Fix repository lowercase name
      uses: Entepotenz/change-string-case-action-min-dependencies@v1
      with:
        string: ${{ github.repository }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ steps.repo-name.outputs.lowercase }}:latest