name: Playwright Test
description: Run Playwright tests
inputs:
  retention-days:
    description: 'Playwright report retention days'
    required: true
    default: '30'
runs:
  using: "composite"
  steps:
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      shell: bash

    - name: Run Playwright tests
      run: npx playwright test
      shell: bash

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: ${{ inputs.retention-days }}
