name: Push Image

on:
  push:
    branches: [main]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/playwright
        with:
          retention-days: 30
      - uses: ./.github/actions/image
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
